ARG VERSAO_ELK

# https://www.docker.elastic.co/
FROM docker.elastic.co/elasticsearch/elasticsearch:${VERSAO_ELK}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu